# Generated by Django 5.2.12 on 2026-03-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="pages",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
